#!/usr/bin/env python3
#
# Author: palb91
# Date:   2022
#
# `config-cycle` per root domain, not current subdomain (#5408)
#
# In config.py:
#   bind('cj', 'spawn -u domcycle content.javascript.enabled')
#
# Usage:
#   domcycle <setting> [URL]
#
# URL defaults to QUTE_URL

import os
import sys
import tldextract


def exequte(command):
    with open(os.getenv('QUTE_FIFO'), 'w') as fifo:
        fifo.write(command + '\n')


if len(sys.argv) < 2:
    usage = 'usage: spawn -u -- domcycle <setting> [URL]'
    execute(f'message-error No setting provided ({usage})')
    sys.exit(2)


setting = sys.argv[1]
url     = sys.argv[2] if len(sys.argv) > 2 else os.getenv('QUTE_URL')
pattern = '*://*.' + '.'.join(tldextract.extract(url)[-2:]) + '/*'


# Handle specific urls
for scheme in ['file', 'qute']:
    if url.lstrip(f'{scheme}://') != url:
        pattern = f'{scheme}:///*'


# Note: reload in script because it didn't work well in binding (;; reload)
exequte(f'config-cycle -ptu {pattern} {setting}')
exequte('reload -f')
